app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('auth/login',        ['as' => 'auth.login',      'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login',       ['as' => 'auth.accept',     'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout',       ['as' => 'auth.logout',     'uses' => 'Auth\AuthController@getLogout']);

// Registration routes...
Route::get('auth/register',        ['as' => 'auth.register',   'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register',       ['as' => 'auth.store',     'uses' => 'Auth\AuthController@postRegister']);
Route::get('auth/email-available', ['as' => 'auth.email-available', 'uses' => 'Auth\AuthController@getEmailAvailable']);

// Password reset link request routes...
Route::get('password/email',    ['as' => 'password.email',  'uses' => 'Auth\PasswordController@getEmail']);
Route::post('password/email',   ['as' => 'password.send',   'uses' => 'Auth\PasswordController@postEmail']);

// Password reset routes...
Route::get('password/reset/{token}',    ['as' => 'password.reset',  'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset',           ['as' => 'password.accept', 'uses' => 'Auth\PasswordController@postReset']);

// Profile routes...
Route::get('profile/show/{id}',   ['as' => 'profile.show',    'uses' => 'ProfileController@show']);
Route::get('profile/edit',        ['as' => 'profile.edit',    'uses' => 'ProfileController@edit']);
Route::put('profile/edit',        ['as' => 'profile.update',  'uses' => 'ProfileController@update']);

// Pages routes...
Route::get('/',              ['as' => 'home',    'uses' => 'PagesController@home']);
Route::get('about',          ['as' => 'about',   'uses' => 'PagesController@about']);
Route::get('leaderboard',    ['as' => 'leaderboard', 'uses' => 'PagesController@leaders']);
Route::get('contact',        ['as' => 'contact', 'uses' => 'PagesController@contact']);

Route::resource('missions', 'MissionsController');
Route::resource('missions.attempts', 'AttemptsController', [ 'only' => ['store', 'update', 'edit', 'destroy'] ]);

// APIs
Route::get('api/weather',              ['as' => 'api.weather',    'uses' => 'APIController@weather']);

app/Mission.php
<?php

namespace App;

use Codesleeve\Stapler\ORM\StaplerableInterface;
use Codesleeve\Stapler\ORM\EloquentTrait;

use Illuminate\Database\Eloquent\Model;

class Mission extends Model implements StaplerableInterface
{
    use EloquentTrait;

	protected $fillable = ['title', 'description', 'photo'];

	public function __construct(array $attributes = array()) {
        $this->hasAttachedFile('photo', [
            'styles' => [
                'hero' => [
                    'dimensions' => '1170x400#',
                    'convert_options' => ['quality' => 60]
                    ],
                'medium' => '500x500',
                'thumb'  => '100x100'
            ]
        ]);

        parent::__construct($attributes);
    }

    function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    function attempts()
    {
        return $this->hasMany(Attempt::class);
    }
}

app/Http/Controllers/MissionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CreateMissionRequest;
use App\Http\Requests\UpdateMissionRequest;

use App\Http\Controllers\Controller;

use App\Mission;
use DB;

class MissionsController extends Controller
{

    function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $missions = Mission::with('user')->get();

        return view('missions.index', compact('missions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $mission = new Mission;
        return view('missions.create', compact('mission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(CreateMissionRequest $request)
    {
        $mission = new Mission($request->all());
        $mission->user()->associate($request->user());
        $mission->save();

        return redirect()->route('missions.show', $mission->id)
            ->with('status.success', 'Success! Your mission is now live!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $mission = Mission::findOrFail($id);
        $attempts = $mission->attempts()->with('user')->get();

        $attemptTally = count($attempts);
        $successTally = count($mission->attempts()->where('status', 'success')->get());

        $missionSuccess = DB::select('select attempts.*, users.name, users.id
            FROM attempts
            JOIN users ON user_id=users.id
            where status = "success" AND mission_id = ?', [$mission->id]);


        return view('missions.show', compact('mission', 'attempts', 'attemptTally', 'successTally', 'missionSuccess'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $mission = Mission::find($id);
        return view('missions.edit', compact('mission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(UpdateMissionRequest $request, $id)
    {
        $mission = Mission::findOrFail($id);
        $mission->fill($request->all());
        $mission->save();

        return redirect()->route('missions.show', $id)
            ->with('status.success', 'Success! Your mission is now updated!');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/missions/_attempt_class.blade.php
@if($attempt->status === 'success')
alert alert-success
@elseif($attempt->status === 'almost')
alert alert-warning
@elseif($attempt->status === 'miss')
alert alert-danger
@else
alert alert-info
@endif

resources/views/missions/_form.blade.php
@if(count($errors) > 0)
  <div class="alert alert-danger text-center">
    There were problems with your form. Please fix them.
  </div>
@endif

<div class="form-group {{ $errors->has('title') ? 'has-error text-danger' : '' }}">
  <label for="title" class="col-sm-2 control-label">Mission Title</label>
  <div class="col-sm-10">
    {!! Form::text('title', $mission->title, ['class' => 'form-control']) !!}
    @include('partials.error-help-block', ['field' => 'title'])
  </div> {{-- /.col-sm-10 --}}
</div> {{-- /.form-group --}}
<div class="form-group {{ $errors->has('title') ? 'has-error text-danger' : '' }}">
  <label for="description" class="col-sm-2 control-label">Description</label>
  <div class="col-sm-10">
    {!! Form::textarea('description', $mission->description, ['class' => 'form-control']) !!}
    @include('partials.error-help-block', ['field' => 'description'])
  </div> {{-- /.col-sm-10 --}}
</div> {{-- /.form-group --}}

<div class="form-group {{ $errors->has('photo') ? 'has-error text-danger' : '' }}">
  <label for="photo" class="col-sm-2 control-label">Answer Photo</label>
  <div class="col-sm-10">
    {!! Form::file('photo', ['class' => 'form-control']) !!}
    @include('partials.error-help-block', ['field' => 'photo'])
  </div> {{-- /.col-sm-10 --}}
</div> {{-- /.form-group --}}

resources/views/missions/create.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">

    <h1 class="text-center">Create a new mission</h1>

    {!! Form::open(['route' => 'missions.store', 'class' => 'form-horizontal', 'files' => true]) !!}

      @include('missions._form')

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Create Mission</button>
        </div> {{-- /.col-sm-10 --}}
      </div> {{-- /.form-group --}}

    {!! Form::close() !!} {{-- /.form --}}

  </div> {{-- /.container --}}
@endsection

resources/views/missions/edit.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">

    <h1 class="text-center">Edit mission</h1>

    {!! Form::open(['route' => ['missions.update', $mission->id], 'class' => 'form-horizontal', 'files' => true]) !!}

      {!! Form::hidden('_method', 'PUT') !!}

      @include('missions._form')

      <div class="form-group">
      <label class="col-sm-2 control-label">Current Photo</label>
        <div class="col-sm-10">
          <p><img src="{{ $mission->photo->url('thumb') }}" alt="" class="img-rounded"></p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Update Mission</button>
        </div> {{-- /.col-sm-10 --}}
      </div> {{-- /.form-group --}}

    {!! Form::close() !!} {{-- /.form --}}

  </div> {{-- /.container --}}
@endsection

resources/views/missions/index.blade.php
@extends('layouts.master')

@section('content')
	<div class="container">
		<h1>Missions</h1>
		<ul>
			@foreach($missions as $mission)
				<li>
					<a href="{{ route('missions.show', $mission->id) }}">
						{{ $mission->title }} 
					</a>
					— {{ $mission->user->name }}
				</li>
			@endforeach
		</ul>
		<p>
			<a href="{{ route('missions.create') }}" class="btn btn-success">
				<span class="glyphicon glyphicon-plus"></span> Create Mission
			</a>
		</p>
	</div>

@endsection

resources/views/missions/show.blade.php
@extends('layouts.master')

@section('content')
	<div class="container">
    @if(count($errors) > 0)
      <div class="alert alert-danger">There were problems with your attempt form. Please scroll down and fix them.</div>
    @endif

		<h1>{{ $mission->title }}</h1>
		<p>
      <strong>Made by:</strong>
      {{ $mission->user->name }}
      @if(Auth::check())
        @if(Auth::user()->id === $mission->user->id)
          (You!)
        @endif
      @endif
    </p>
		<p>{{ $mission->description }}</p>
    @if(Auth::check())
  		@if(Auth::user()->id === $mission->user->id)
        <p><img src="{{ $mission->photo->url('hero') }}" alt=""></p>
        <p><a href="{{ route('missions.edit', $mission->id) }}" class="btn btn-default">
        <span class="glyphicon glyphicon-pencil"></span> Edit Mission</a></p>
      @endif
    @endif


    <h2>Attempts — {{ $successTally }} / {{ $attemptTally }} attempts successful</h2>
    <h3>Successful Users:</h3>
     @if($missionSuccess)
     <ul>
       @foreach( $missionSuccess as $successfulUser )

         <li><a href="{{ route('profile.show', $successfulUser->id) }}">{{ $successfulUser->name }}</a></li>

       @endforeach
     </ul>
     @else
       <p>No successful users founds</p>

     @endif

    <div class="container">
    @foreach($attempts as $attempt)
      @if(Auth::check())
        @if(Auth::user()->id === $mission->user->id || Auth::user()->id === $attempt->user->id)

          <div class="row">
            <div class="col-sm-2">
              <p><img src="{{ $attempt->photo->url('thumb') }}" alt=""
                class="img-rounded @include('missions._attempt_class', ['attempt' => $attempt]) "></p>
            </div>
            <div class="col-sm-10">
              <p>{{ $attempt->user->name }}</p>
              <p>
                <a href="{{ route('missions.attempts.edit', [$mission->id, $attempt->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Edit Attempt</a>

              @if(Auth::user()->id === $mission->user->id)
                {!! Form::open(['route' => ['missions.attempts.update', $attempt->mission_id, $attempt->id], 'class' => 'form-horizontal attempts-update', 'files' => true, 'method' => 'PUT', 'data-attempt-id' => $attempt->id]) !!}
                  <div class="btn-group" role="group" aria-label="Change Status">
                    <button type="submit" class="btn btn-success @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'success'])" name="status" value="success">Success</button>
                    <button type="submit" class="btn btn-warning @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'almost'])" name="status" value="almost">Almost</button>
                    <button type="submit" class="btn btn-danger @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'miss'])" name="status" value="miss">Miss</button>
                    <button type="submit" class="btn btn-info @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'unchecked'])" name="status" value="unchecked">Unchecked</button>
                  </div>
                {!! Form::close() !!}
              @endif
              </p>
            </div>
          </div>
        @endif
      @endif
    @endforeach
    </div>

		<h3>Add New Attempt</h3>
    @if(Auth::check() && Auth::user()->id !== $mission->user->id)
      {!! Form::open(['route' => ['missions.attempts.store', $mission->id], 'class' => 'form-horizontal', 'files' => true]) !!}

        <div class="form-group {{ $errors->has('photo') ? 'has-error text-danger' : '' }}">
          <label for="photo" class="col-sm-2 control-label">Attempt Photo</label>
          <div class="col-sm-10">
            {!! Form::file('photo', ['class' => 'form-control', 'rows' => '5']) !!}
            @include('partials.error-help-block', ['field' => 'photo'])
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Submit Attempt</button>
          </div>
        </div>
      {!! Form::close() !!}
    @elseif(Auth::check() && Auth::user()->id === $mission->user->id)
      <p>You can't submit an attempt on your own mission!</p>
    @else
      <p><a href="{{ route('auth.login') }}">Log in</a> to submit an attempt on this mission.</p>
    @endif
	</div>

@endsection